apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
  - list:
      elements:
        - cluster: dev
          url: https://kubernetes.default.svc
          namespace: dev
          githubUrl: https://github.com/bcovies/argocd-demo/

        - cluster: stage
          url: https://kubernetes.default.svc
          namespace: stage
          githubUrl: https://github.com/bcovies/argocd-demo/

        - cluster: prod
          url: https://kubernetes.default.svc
          namespace: prod
          githubUrl: https://github.com/bcovies/argocd-demo/

  template:
    metadata:
      name: '{{cluster}}-guestbook'
    spec:
      project: default
      source:
        directory:
          recuser: true
        repoURL: '{{ githubUrl }}' # Hosts the manifests files
        targetRevision: test-argo # Branch 
        path: ms # path to the files
        helm:
          valueFiles:
            - environments/{{namespace}}.yaml
            - common/values.yaml
      destination:
        server: '{{url}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true  