apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
  - list:
      elements:
      - cluster: dev
        url: https://kubernetes.default.svc
        namespace: dev
      - cluster: prod
        url: https://kubernetes.default.svc
        namespace: prod
      - cluster: preprod
        url: https://kubernetes.default.svc
        namespace: preprod
  template:
    metadata:
      name: '{{cluster}}-guestbook'
    spec:
      project: default
      source:
        repoURL: https://github.com/bcovies/argocd-demo/ # Hosts the manifests files
        targetRevision: test-argo # Branch 
        path: rename-service/templates # path to the files
        helm:
          valueFiles:
            - environments/{{namespace}}.yaml
      # source:
      #   repoURL: https://github.com/infra-team/cluster-deployments.git
      #   targetRevision: HEAD
      #   path: guestbook/{{cluster}}
      destination:
        server: '{{url}}'
        namespace: '{{namespace}}'