apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.generic.artifactId }}
  name: {{ .Values.generic.artifactId }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.generic.artifactId }}
  ports:
    - port: 80
      targetPort: {{ .Values.service.targetPort }}
      name: http